<template>
  <div class="test">
    <my-header :title="title" :isHomePage="true"></my-header>
    <div>{{msg}} </div>
    <div class="square"></div>
  </div>
</template>

<script>
  import myHeader from "@/components/header/header.vue";
  export default {
    name: 'test',
    data () {
      return {
        msg: 'Welcome to Your Vue.js App',
        title:'test',
        json:[
          {
            "id": 0,
            "pid": null,
            "name": "总体视图"
          }, {
            "id": 1,
            "pid": 0,
            "name": "收入"
          }, {
            "id": 38,
            "pid": 0,
            "name": "用户"
          }, {
            "id": 73,
            "pid": 0,
            "name": "业务量"
          }, {
            "id": 126,
            "pid": 0,
            "name": "市场竞争(高校)"
          }, {
            "id": 2,
            "pid": 1,
            "name": "出账收入"
          }, {
            "id": 36,
            "pid": 1,
            "name": "缴费"
          }, {
            "id": 39,
            "pid": 38,
            "name": "到达"
          }, {
            "id": 47,
            "pid": 38,
            "name": "新增"
          }, {
            "id": 61,
            "pid": 38,
            "name": "净增"
          }, {
            "id": 74,
            "pid": 73,
            "name": "话音业务"
          }, {
            "id": 86,
            "pid": 73,
            "name": "数据业务"
          }, {
            "id": 99,
            "pid": 73,
            "name": "流量业务"
          }, {
            "id": 115,
            "pid": 73,
            "name": "校园产品"
          }, {
            "id": 127,
            "pid": 126,
            "name": "到达"
          }, {
            "id": 139,
            "pid": 126,
            "name": "新增"
          }, {
            "id": 153,
            "pid": 126,
            "name": "净增"
          }, {
            "id": 3,
            "pid": 2,
            "name": "语音收入"
          }, {
            "id": 8,
            "pid": 2,
            "name": "数据业务收入"
          }, {
            "id": 21,
            "pid": 2,
            "name": "流量业务收入"
          }, {
            "id": 26,
            "pid": 2,
            "name": "增值业务收入"
          }, {
            "id": 29,
            "pid": 2,
            "name": "校园产品收入"
          }, {
            "id": 32,
            "pid": 2,
            "name": "固定费收入"
          }, {
            "id": 35,
            "pid": 2,
            "name": "ARPU"
          }, {
            "id": 37,
            "pid": 36,
            "name": "当期户均余额"
          }, {
            "id": 182,
            "pid": 36,
            "name": "日累计人均预存款"
          }, {
            "id": 183,
            "pid": 36,
            "name": "当日人均预存款"
          }, {
            "id": 40,
            "pid": 39,
            "name": "到达用户数"
          }, {
            "id": 48,
            "pid": 47,
            "name": "新增用户数"
          }, {
            "id": 55,
            "pid": 47,
            "name": "新增市场份额"
          }, {
            "id": 62,
            "pid": 61,
            "name": "净增用户数"
          }, {
            "id": 69,
            "pid": 61,
            "name": "净增市场份额"
          }, {
            "id": 75,
            "pid": 74,
            "name": "本地通话"
          }, {
            "id": 78,
            "pid": 74,
            "name": "长途通话"
          }, {
            "id": 81,
            "pid": 74,
            "name": "漫游通话"
          }, {
            "id": 87,
            "pid": 86,
            "name": "飞信活跃用户数"
          }, {
            "id": 89,
            "pid": 86,
            "name": "彩铃订购用户数"
          }, {
            "id": 91,
            "pid": 86,
            "name": "短信条数"
          }, {
            "id": 93,
            "pid": 86,
            "name": "彩信条数"
          }, {
            "id": 95,
            "pid": 86,
            "name": "GPRS流量"
          }, {
            "id": 97,
            "pid": 86,
            "name": "WLAN时长"
          }, {
            "id": 107,
            "pid": 99,
            "name": "GPRS业务"
          }, {
            "id": 112,
            "pid": 99,
            "name": "wlan业务"
          }, {
            "id": 116,
            "pid": 115,
            "name": "校园v网"
          }, {
            "id": 128,
            "pid": 127,
            "name": "到达用户数"
          }, {
            "id": 135,
            "pid": 127,
            "name": "到达市场份额"
          }, {
            "id": 140,
            "pid": 139,
            "name": "新增用户数"
          }, {
            "id": 147,
            "pid": 139,
            "name": "新增市场份额"
          }, {
            "id": 154,
            "pid": 153,
            "name": "净增用户数"
          }, {
            "id": 161,
            "pid": 153,
            "name": "净增市场份额"
          }, {
            "id": 4,
            "pid": 3,
            "name": "本地通话收入"
          }, {
            "id": 6,
            "pid": 3,
            "name": "长途通话收入"
          }, {
            "id": 9,
            "pid": 8,
            "name": "飞信"
          }, {
            "id": 11,
            "pid": 8,
            "name": "彩铃"
          }, {
            "id": 13,
            "pid": 8,
            "name": "短信"
          }, {
            "id": 15,
            "pid": 8,
            "name": "彩信"
          }, {
            "id": 17,
            "pid": 8,
            "name": "GPRS"
          }, {
            "id": 19,
            "pid": 8,
            "name": "WLAN"
          }, {
            "id": 22,
            "pid": 21,
            "name": "GPRS业务收入"
          }, {
            "id": 24,
            "pid": 21,
            "name": "WLAN业务收入"
          }, {
            "id": 27,
            "pid": 26,
            "name": "语音增值业务收入"
          }, {
            "id": 30,
            "pid": 29,
            "name": "V网收入"
          }, {
            "id": 33,
            "pid": 32,
            "name": "月租费"
          }, {
            "id": 41,
            "pid": 40,
            "name": "移动"
          }, {
            "id": 43,
            "pid": 40,
            "name": "电信C网"
          }, {
            "id": 45,
            "pid": 40,
            "name": "联通G网"
          }, {
            "id": 49,
            "pid": 48,
            "name": "移动"
          }, {
            "id": 51,
            "pid": 48,
            "name": "联通"
          }, {
            "id": 53,
            "pid": 48,
            "name": "电信"
          }, {
            "id": 56,
            "pid": 55,
            "name": "移动"
          }, {
            "id": 57,
            "pid": 55,
            "name": "联通"
          }, {
            "id": 59,
            "pid": 55,
            "name": "电信"
          }, {
            "id": 63,
            "pid": 62,
            "name": "移动"
          }, {
            "id": 65,
            "pid": 62,
            "name": "联通"
          }, {
            "id": 67,
            "pid": 62,
            "name": "电信"
          }, {
            "id": 70,
            "pid": 69,
            "name": "移动"
          }, {
            "id": 71,
            "pid": 69,
            "name": "联通"
          }, {
            "id": 72,
            "pid": 69,
            "name": "电信"
          }, {
            "id": 76,
            "pid": 75,
            "name": "市话主叫时长"
          }, {
            "id": 77,
            "pid": 75,
            "name": "市话被叫时长"
          }, {
            "id": 79,
            "pid": 78,
            "name": "长途主叫时长"
          }, {
            "id": 80,
            "pid": 78,
            "name": "长途被叫时长"
          }, {
            "id": 82,
            "pid": 81,
            "name": "省内漫游主叫时长"
          }, {
            "id": 83,
            "pid": 81,
            "name": "省内漫游被叫时长"
          }, {
            "id": 84,
            "pid": 81,
            "name": "省际漫游主叫时长"
          }, {
            "id": 85,
            "pid": 81,
            "name": "省际漫游被叫时长"
          }, {
            "id": 101,
            "pid": 107,
            "name": "手机上网用户数"
          }, {
            "id": 103,
            "pid": 107,
            "name": "手机上网普及率"
          }, {
            "id": 105,
            "pid": 107,
            "name": "T网手机上网用户数"
          }, {
            "id": 108,
            "pid": 107,
            "name": "GPRS计费流量"
          }, {
            "id": 110,
            "pid": 107,
            "name": "T网计费流量"
          }, {
            "id": 184,
            "pid": 107,
            "name": "T网计费流量占比"
          }, {
            "id": 113,
            "pid": 112,
            "name": "WLAN时长"
          }, {
            "id": 117,
            "pid": 116,
            "name": "校园V网用户数"
          }, {
            "id": 119,
            "pid": 116,
            "name": "校园V网通话用户数"
          }, {
            "id": 121,
            "pid": 116,
            "name": "校园V网普及率"
          }, {
            "id": 122,
            "pid": 116,
            "name": "V网通话时长"
          }, {
            "id": 124,
            "pid": 116,
            "name": "V网通话次数"
          }, {
            "id": 129,
            "pid": 128,
            "name": "移动"
          }, {
            "id": 131,
            "pid": 128,
            "name": "电信C网"
          }, {
            "id": 133,
            "pid": 128,
            "name": "联通G网"
          }, {
            "id": 136,
            "pid": 135,
            "name": "移动"
          }, {
            "id": 137,
            "pid": 135,
            "name": "电信C网"
          }, {
            "id": 138,
            "pid": 135,
            "name": "联通G网"
          }, {
            "id": 141,
            "pid": 140,
            "name": "移动"
          }, {
            "id": 143,
            "pid": 140,
            "name": "联通"
          }, {
            "id": 145,
            "pid": 140,
            "name": "电信"
          }, {
            "id": 148,
            "pid": 147,
            "name": "移动"
          }, {
            "id": 149,
            "pid": 147,
            "name": "联通"
          }, {
            "id": 151,
            "pid": 147,
            "name": "电信"
          }, {
            "id": 155,
            "pid": 154,
            "name": "移动"
          }, {
            "id": 157,
            "pid": 154,
            "name": "联通"
          }, {
            "id": 159,
            "pid": 154,
            "name": "电信"
          }, {
            "id": 162,
            "pid": 161,
            "name": "移动"
          }, {
            "id": 163,
            "pid": 161,
            "name": "联通"
          }, {
            "id": 164,
            "pid": 161,
            "name": "电信"
          }
        ],
      }
    },
    created(){ 
    },
    mounted(){},
    methods:{
    },
    components: {
      myHeader
    }
  }
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
    /* css实现宽度为浏览器20% 的正方形 */
    .square{
      width:20%;
      padding-bottom:20%;
      height:0;
      background-color: aqua;
      margin:0 auto;
    }
</style>
